Repository little-spoon-dev/design-system, pull requests merged in 2021-09, with the labels that each got.

#7 feat(storybook): initialize storybook LS-1629
  .lintstagedrc.json
  README.md
  package.json
  packages/storybook/.eslintrc.json
  packages/storybook/.storybook/main.js
  packages/storybook/.storybook/preview.js
  packages/storybook/README.md
  packages/storybook/package.json
  packages/storybook/src/stories/Button.stories.tsx
  packages/storybook/src/stories/Button.tsx
  packages/storybook/src/stories/Header.stories.tsx
  packages/storybook/src/stories/Header.tsx
  packages/storybook/src/stories/Introduction.stories.mdx
  packages/storybook/src/stories/Page.stories.tsx
  packages/storybook/src/stories/Page.tsx
  packages/storybook/src/stories/assets/code-brackets.svg
  packages/storybook/src/stories/assets/colors.svg
  packages/storybook/src/stories/assets/comments.svg
  packages/storybook/src/stories/assets/direction.svg
  packages/storybook/src/stories/assets/flow.svg
  packages/storybook/src/stories/assets/plugin.svg
  packages/storybook/src/stories/assets/repo.svg
  packages/storybook/src/stories/assets/stackalt.svg
  packages/storybook/src/stories/button.css
  packages/storybook/src/stories/header.css
  packages/storybook/src/stories/page.css
  packages/storybook/tsconfig.json
  yarn.lock
Labels: feature

#13 feat(storybook): add stories for theme colors LS-1711
  packages/storybook/package.json
  packages/storybook/src/stories/Colors.stories.tsx
  packages/storybook/src/stories/Colors.tsx
Labels: feature

#25 ci(root): fix release-please workflow LS-1727
  .github/workflows/release-please.yml
  release-please-config.json
Labels: bug

#24 feat(theme): add shade tokens to theme LS-1726
  packages/theme/__tests__/__snapshots__/index.test.ts.snap
  packages/theme/src/colors/token.ts
Labels: feature

#30 docs: document release LS-1755
  .github/workflows/publish.yml
  README.md
  docs/CONTRIBUTING.md
Labels: chore, documentation

#33 feat(storybook): render changelog for all packages LS-1731
  .gitignore
  packages/storybook/.gitignore
  packages/storybook/package.json
  packages/storybook/scripts/copy-changelog.ts
  packages/storybook/src/stories/Button.stories.tsx
  packages/storybook/src/stories/Colors.stories.tsx
  packages/storybook/src/stories/Fonts.stories.tsx
  packages/storybook/src/stories/Fonts.tsx
Labels: feature

#38 chore(all): default noEmit to true in root tsconfig.json LS-1780
  packages/button/tsconfig.json
  packages/storybook/tsconfig.json
  packages/theme/tsconfig.json
  scripts/template/tsconfig.json
  tsconfig.json
Labels: chore

#50 refactor: tidy button and stories LS-1789
  .eslintrc.json
  packages/button/__tests__/Button.test.tsx
  packages/button/src/ButtonBase.tsx
  packages/storybook/src/stories/Button.stories.tsx
  packages/storybook/src/stories/Header.stories.tsx
  packages/storybook/src/stories/Header.tsx
  packages/storybook/src/stories/Page.stories.tsx
  packages/storybook/src/stories/Page.tsx
Labels: refactor

#52 fix(scripts): fix JSON stringify in `create-package` script LS-1793
  release-please-config.json
  scripts/create-package.ts
  yarn.lock
Labels: chore

#54 chore(react-template): tidy jest.config.ts LS-1794
  templates/react-template/jest.config.ts
Labels: chore

#63 docs(root): update CONTRIBUTING with Lerna release gotchas LS-1809
  docs/CONTRIBUTING.md
Labels: documentation

#64 chore(storybook): remove example stories from storybook LS-1814
  packages/storybook/src/stories/Button.tsx
  packages/storybook/src/stories/Header.stories.tsx
  packages/storybook/src/stories/Header.tsx
  packages/storybook/src/stories/Introduction.stories.mdx
  packages/storybook/src/stories/Page.stories.tsx
  packages/storybook/src/stories/Page.tsx
  packages/storybook/src/stories/button.css
  packages/storybook/src/stories/header.css
  packages/storybook/src/stories/page.css
Labels: chore

#66 feat(icons): add arrow icon LS-1817
  README.md
  docs/CONTRIBUTING.md
  packages/icons/.eslintrc.json
  packages/icons/README.md
  packages/icons/__tests__/ArrowIcon.test.tsx
  packages/icons/__tests__/index.test.ts
  packages/icons/jest.config.ts
  packages/icons/package.json
  packages/icons/src/ArrowBase.tsx
  packages/icons/src/ArrowIcon.tsx
  packages/icons/src/index.ts
  packages/icons/tsconfig.json
  packages/storybook/package.json
  packages/storybook/src/stories/ArrowIcon.stories.tsx
  packages/ui/__tests__/index.test.ts
  packages/ui/icons/ArrowIcon/index.ts
  packages/ui/icons/index.ts
Labels: feature

#65 feat: allow button to render as a different component LS-1777
  .eslintrc.json
  docs/CONTRIBUTING.md
  packages/button/README.md
  packages/button/__tests__/Button.test.tsx
  packages/button/src/Button.tsx
  packages/button/src/ButtonBase.tsx
  packages/storybook/src/stories/Button.stories.tsx
  packages/storybook/tsconfig.json
Labels: feature

#71 ci: run auto-approve on pull_request_target in build
  .github/workflows/build.yml
  lerna.json
Labels: chore

#78 feat(divider-curve): add divider curve variants to design system LS-1842
  packages/divider/.eslintrc.json
  packages/divider/README.md
  packages/divider/__tests__/Divider.test.tsx
  packages/divider/__tests__/index.test.ts
  packages/divider/jest.config.ts
  packages/divider/package.json
  packages/divider/src/Divider.tsx
  packages/divider/src/index.ts
  packages/divider/tsconfig.json
  packages/storybook/package.json
  packages/storybook/src/stories/Divider.stories.tsx
  packages/ui/Divider/index.ts
  packages/ui/__tests__/__snapshots__/index.test.ts.snap
  packages/ui/index.ts
  packages/ui/package.json
Labels: feature
