Repository little-spoon-dev/design-system, pull requests merged in 2021-11, with the labels that each got.

#163 feat(button): add variant `tertiary` LS-2152
  packages/button/__tests__/Button.test.tsx
  packages/button/src/Button.tsx
  packages/button/src/ButtonBase.tsx
  packages/storybook/src/stories/Button.stories.tsx
Labels: bug, feature

#165 feat(tag): add padding between text and icon LS-2201
  packages/tag/src/styled.tsx
Labels: feature

#170 build(root): update yarn.lock
  yarn.lock
Labels: dependencies

#173 feat: add Link LS-2202
  README.md
  packages/link/.eslintrc.json
  packages/link/README.md
  packages/link/__tests__/Link.test.tsx
  packages/link/__tests__/index.test.ts
  packages/link/jest.config.ts
  packages/link/package.json
  packages/link/src/Link.tsx
  packages/link/src/LinkBase.tsx
  packages/link/src/index.ts
  packages/link/tsconfig.json
  packages/storybook/src/stories/Link.stories.tsx
  packages/ui/Link/index.ts
  packages/ui/__tests__/__snapshots__/index.test.ts.snap
  packages/ui/index.ts
  packages/ui/package.json
Labels: feature

#175 build(root): upgrade devDependencies LS-2324
  package.json
  yarn.lock
Labels: dependencies
