Repository little-spoon-dev/design-system, pull requests merged in 2022-08, with the labels that each got.

#560 fix(storybook): set NODE_OPTIONS to openssl-legacy-provider
  .nvmrc
  packages/storybook/package.json
Labels: bug

#574 fix: improve Storybook stories for label LS-3794
  packages/breadcrumbs/src/styled.tsx
  packages/label/CHANGELOG.md
  packages/label/README.md
  packages/label/src/Label.tsx
  packages/label/src/LabelBase.tsx
  packages/storybook/src/stories/Label.stories.tsx
  packages/storybook/src/stories/icons/ArrowIcon.stories.tsx
  packages/storybook/src/stories/icons/FilterIcon.stories.tsx
  packages/theme/README.md
Labels: bug

#583 feat(icons): add checkmark and exclamation mark icons LS-3819
  packages/icons/README.md
  packages/icons/__tests__/CheckIcon.test.tsx
  packages/icons/__tests__/ExclamationIcon.test.tsx
  packages/icons/src/CheckBase.tsx
  packages/icons/src/CheckIcon.tsx
  packages/icons/src/ExclamationBase.tsx
  packages/icons/src/ExclamationIcon.tsx
  packages/icons/src/index.ts
  packages/storybook/src/stories/icons/CheckIcon.stories.tsx
  packages/storybook/src/stories/icons/ExclamationIcon.stories.tsx
Labels: feature

#589 feat(icons): create subtract icon LS-3892
  packages/icons/README.md
  packages/icons/__tests__/SubtractIcon.test.tsx
  packages/icons/src/SubtractIcon.tsx
  packages/icons/src/SubtractIconBase.tsx
  packages/icons/src/index.ts
  packages/storybook/src/stories/icons/SubtractIcon.stories.tsx
Labels: feature

#608 docs(packages): tidy headings in CHANGELOG.md
  packages/alert/CHANGELOG.md
  packages/icons/CHANGELOG.md
  packages/storybook/CHANGELOG.md
  packages/theme/CHANGELOG.md
  packages/ui/CHANGELOG.md
Labels: documentation
